<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ZZZae.Protocol</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZZZae.Core\ZZZae.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource
      Include="Metadata\AchievementInfo.json"
      LogicalName="ZZZae.Metadata.AchievementInfo.json"
    />
  </ItemGroup>
</Project>
